Repository zigpy/bellows, pull requests merged in 2020-03, with the labels that each got.

#224 Doh
  bellows/zigbee/application.py
Labels: fix

#222 Close thread on UART opening failure.
  bellows/uart.py
  tests/test_uart.py
Labels: bug

#223 Add probe EZSP method.
  bellows/exception.py
  bellows/ezsp.py
  setup.py
  tests/test_ezsp.py
Labels: feature

#226 ezsp: fix incorrect ezsp_version reference
  bellows/ezsp.py
Labels: bug
